/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface MockVerifierInterface extends utils.Interface {
  functions: {
    "verify(uint256,address,uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "verify"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "verify",
    values: [BigNumberish, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {
    "Verified(uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Verified"): EventFragment;
}

export interface VerifiedEventObject {
  userId: BigNumber;
  userAddr: string;
  tokenId: BigNumber;
}
export type VerifiedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  VerifiedEventObject
>;

export type VerifiedEventFilter = TypedEventFilter<VerifiedEvent>;

export interface MockVerifier extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockVerifierInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    verify(
      userId_: BigNumberish,
      userAddr_: string,
      tokenId_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  verify(
    userId_: BigNumberish,
    userAddr_: string,
    tokenId_: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    verify(
      userId_: BigNumberish,
      userAddr_: string,
      tokenId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Verified(uint256,address,uint256)"(
      userId?: BigNumberish | null,
      userAddr?: string | null,
      tokenId?: null
    ): VerifiedEventFilter;
    Verified(
      userId?: BigNumberish | null,
      userAddr?: string | null,
      tokenId?: null
    ): VerifiedEventFilter;
  };

  estimateGas: {
    verify(
      userId_: BigNumberish,
      userAddr_: string,
      tokenId_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    verify(
      userId_: BigNumberish,
      userAddr_: string,
      tokenId_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
