/// <reference types="vite/client" />

interface ImportMetaEnv {
  VITE_ENVIRONMENT: string
  VITE_PORT: string
  VITE_API_URL: string
  VITE_APP_NAME: string

  WALLET_CONNECT_PROJECT_ID: string

  AUTH_BJJ_CREDENTIAL_HASH: string

  DEMO_VERIFIER_CONTRACT_ADDRESS_SEPOLIA: string
  ZKP_QUERIES_STORAGE_CONTRACT_ADDRESS_SEPOLIA: string
  STATE_V2_CONTRACT_ADDRESS_SEPOLIA: string

  DEMO_VERIFIER_CONTRACT_ADDRESS_POLYGON: string
  ZKP_QUERIES_STORAGE_CONTRACT_ADDRESS_POLYGON: string
  STATE_V2_CONTRACT_ADDRESS_POLYGON: string

  DEMO_VERIFIER_CONTRACT_ADDRESS_GOERLI: string
  ZKP_QUERIES_STORAGE_CONTRACT_ADDRESS_GOERLI: string
  STATE_V2_CONTRACT_ADDRESS_GOERLI: string
}

interface Document {
  ENV: ImportMetaEnv
}
